import { LoadingProvider } from "@/components/LoadingContext";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link
          href="https://fonts.googleapis.com/css2?family=Raleway:wght@400;500;700&display=swap"
          rel="stylesheet"
        />
      </head>
      <LoadingProvider>
        <body
          suppressHydrationWarning
          style={{
            margin: 0,
          }}
        >
          {children}
        </body>
      </LoadingProvider>
    </html>
  );
}
